/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2019-02-24 18:10:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class UserLogged_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=windows-1256");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("\"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("function submitForm(x){\r\n");
      out.write("    if(x.id=='id2'){\r\n");
      out.write("       document.getElementById('id2').value='event';\r\n");
      out.write("    }\r\n");
      out.write(" }\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\".datepicker\").datepicker();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction echeck(str) {\r\n");
      out.write("\r\n");
      out.write("\t\tvar at=\"@\"\r\n");
      out.write("\t\tvar dot=\".\"\r\n");
      out.write("\t\tvar lat=str.indexOf(at)\r\n");
      out.write("\t\tvar lstr=str.length\r\n");
      out.write("\t\tvar ldot=str.indexOf(dot)\r\n");
      out.write("\t\tif (str.indexOf(at)==-1){\r\n");
      out.write("\t\talert(\"Invalid E-mail ID\")\r\n");
      out.write("\t\treturn false\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (str.indexOf(at)==-1 || str.indexOf(at)==0 || str.indexOf(at)==lstr){\r\n");
      out.write("\t\talert(\"Invalid E-mail ID\")\r\n");
      out.write("\t\treturn false\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (str.indexOf(dot)==-1 || str.indexOf(dot)==0 || str.indexOf(dot)==lstr){\r\n");
      out.write("\t\talert(\"Invalid E-mail ID\")\r\n");
      out.write("\t\treturn false\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (str.indexOf(at,(lat+1))!=-1){\r\n");
      out.write("\t\talert(\"Invalid E-mail ID\")\r\n");
      out.write("\t\treturn false\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (str.substring(lat-1,lat)==dot || str.substring(lat+1,lat+2)==dot){\r\n");
      out.write("\t\talert(\"Invalid E-mail ID\")\r\n");
      out.write("\t\treturn false\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (str.indexOf(dot,(lat+2))==-1){\r\n");
      out.write("\t\talert(\"Invalid E-mail ID\")\r\n");
      out.write("\t\treturn false\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif (str.indexOf(\" \")!=-1){\r\n");
      out.write("\t\talert(\"Invalid E-mail ID\")\r\n");
      out.write("\t\treturn false\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\treturn true\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction ValidateForm(){\r\n");
      out.write("\t\tvar emailID=document.frmSample.txtEmail\r\n");
      out.write("\r\n");
      out.write("\t\tif ((emailID.value==null)||emailID.value==\"\"){\r\n");
      out.write("\t\talert(\"Please Enter your Email ID\")\r\n");
      out.write("\t\temailID.focus()\r\n");
      out.write("\t\treturn false\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (echeck(emailID.value)==false){\r\n");
      out.write("\t\temailID.value=\"\"\r\n");
      out.write("\t\temailID.focus()\r\n");
      out.write("\t\treturn false\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true\r\n");
      out.write("\t\t}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tbackground: url('Images/welcome.jpg') no-repeat center center fixed;\r\n");
      out.write("\t/* For IE 6 and 7 */\r\n");
      out.write("\t-webkit-background-size: cover;\r\n");
      out.write("\t-moz-background-size: cover;\r\n");
      out.write("\t-o-background-size: cover;\r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tfont-family: cursive;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tfont-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Full-width input fields */\r\n");
      out.write("input[type=text], input[type=password] {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tpadding: 12px 20px;\r\n");
      out.write("\tmargin: 8px 0;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tborder: 1px solid #ccc;\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Set a style for all buttons */\r\n");
      out.write("button {\r\n");
      out.write("\tbackground-color: #4CAF50;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tpadding: 14px 20px;\r\n");
      out.write("\tmargin: 8px 0;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("\tbackground-color: #4CAF50;\r\n");
      out.write("\tcolor: blue;\r\n");
      out.write("\tpadding: 14px 20px;\r\n");
      out.write("\tmargin: 8px 0;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\theight: 50px !important;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button:hover , .card:hover {\r\n");
      out.write("\topacity: 0.8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Extra styles for the cancel button */\r\n");
      out.write(".cancelbtn {\r\n");
      out.write("/* \twidth: auto;\r\n");
      out.write("\tpadding: 10px 18px; */\r\n");
      out.write("\tbackground-color: #f44336;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Center the image and position the close button */\r\n");
      out.write(".imgcontainer {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin: 24px 0 12px 0;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img.avatar {\r\n");
      out.write("\twidth: 40%;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("\tpadding: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span.psw {\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tpadding-top: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* The Modal (background) */\r\n");
      out.write(".modal {\r\n");
      out.write("\tdisplay: none; /* Hidden by default */\r\n");
      out.write("\tposition: fixed; /* Stay in place */\r\n");
      out.write("\tz-index: 1; /* Sit on top */\r\n");
      out.write("\tleft: 0;\r\n");
      out.write("\ttop: 0;\r\n");
      out.write("\twidth: 100%; /* Full width */\r\n");
      out.write("\theight: 100%; /* Full height */\r\n");
      out.write("\toverflow: auto; /* Enable scroll if needed */\r\n");
      out.write("\tbackground-color: rgb(0, 0, 0); /* Fallback color */\r\n");
      out.write("\tbackground-color: rgba(0, 0, 0, 0.4); /* Black w/ opacity */\r\n");
      out.write("\tpadding-top: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Modal Content/Box */\r\n");
      out.write(".modal-content {\r\n");
      out.write("\tbackground-color: #fefefe;\r\n");
      out.write("\tmargin: 5% auto 15% auto;\r\n");
      out.write("\t/* 5% from the top, 15% from the bottom and centered */\r\n");
      out.write("\tborder: 1px solid #888;\r\n");
      out.write("\twidth: 50%; /* Could be more or less, depending on screen size */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* The Close Button (x) */\r\n");
      out.write(".close {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  right: 25px;\r\n");
      out.write("  top: 0;\r\n");
      out.write("  color: #000;\r\n");
      out.write("  font-size: 35px;\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".close:hover, .close:focus {\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add Zoom Animation */\r\n");
      out.write(".animate {\r\n");
      out.write("\t-webkit-animation: animatezoom 0.6s;\r\n");
      out.write("\tanimation: animatezoom 0.6s\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@\r\n");
      out.write("-webkit-keyframes animatezoom {\r\n");
      out.write("\tfrom {-webkit-transform: scale(0)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("to {\r\n");
      out.write("\t-webkit-transform: scale(1)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("@\r\n");
      out.write("keyframes animatezoom {\r\n");
      out.write("\tfrom {transform: scale(0)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("to {\r\n");
      out.write("\ttransform: scale(1)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Change styles for span and cancel button on extra small screens */\r\n");
      out.write("@media screen and (max-width: 300px) {\r\n");
      out.write("\tspan.psw {\r\n");
      out.write("\t\tdisplay: block;\r\n");
      out.write("\t\tfloat: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.cancelbtn {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<h2>Booking Application</h2>\r\n");
      out.write("\r\n");
      out.write("\t<!-- <button onclick=\"document.getElementById('id01').style.display='block'\"\r\n");
      out.write("\t\tclass=\"card\">Make a Booking</button> -->\r\n");
      out.write("\t\t<a class=\"card\" href=\"");
      out.print(request.getContextPath());
      out.write("/event\">View all Bookings</a>\r\n");
      out.write("\t\t<a class=\"card\" onclick=\"document.getElementById('id01').style.display='block'\" href=\"#\" data-toggle=\"modal\" data-target=\"#id01\">Make a Booking</a>\r\n");
      out.write("\t\t<a class=\"card\" onclick=\"document.getElementById('id02').style.display='block'\" href=\"#\" data-toggle=\"modal\" data-target=\"#id02\">Add User</a>\r\n");
      out.write("\t<a class=\"card\" onclick=\"document.getElementById('id03').style.display='block'\" href=\"#\" data-toggle=\"modal\" data-target=\"#id03\">View All Rooms</a>\r\n");
      out.write("\t<a class=\"card\" onclick=\"document.getElementById('id04').style.display='block'\" href=\"#\" data-toggle=\"modal\" data-target=\"#id04\">View Available Rooms</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"id01\" class=\"modal\">\r\n");
      out.write("\r\n");
      out.write("\t\t<form  onSubmit=\"return ValidateForm()\" class=\"modal-content animate\" action=\"booking\">\r\n");
      out.write("\t\t\t   <div class=\"imgcontainer\">\r\n");
      out.write("      <span onclick=\"document.getElementById('id01').style.display='none'\" class=\"close\" title=\"Close Modal\">&times;</span>\r\n");
      out.write("    \r\n");
      out.write("    </div> \r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<label for=\"ln\"><b>Make a Booking</b></label>\r\n");
      out.write("\t\t\t\t <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"FirstName\" name=\"fn\" required> <input\r\n");
      out.write("\t\t\t\t\ttype=\"password\" placeholder=\"LastName\" name=\"ln\" required>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" placeholder=\"email@example.com\"  name=\"txtEmail\"> \r\n");
      out.write("\t\t\t\t\t<input type=\"text\" placeholder=\"Telephone\"  name=\"contact\"> \r\n");
      out.write("\t\t\t\t<div class=\"container\" >\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"from\" id=\"from\" class=\"datepicker\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Check in\" required style=\"display: inline;float:left;\"> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"datepicker\" name=\"to\" id=\"to\" placeholder=\"Check out\" required style=\"display: inline;float:left;\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"container\" style=\"background-color: #f1f1f1\">\r\n");
      out.write("\t\t\t\t<button type=\"Submit\">Confirm</button>\r\n");
      out.write("\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\tonclick=\"document.getElementById('id01').style.display='none'\"\r\n");
      out.write("\t\t\t\t\tclass=\"cancelbtn\">Cancel</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t// Get the modal\r\n");
      out.write("\t\tvar modal = document.getElementById('id01');\r\n");
      out.write("\r\n");
      out.write("\t\t// When the user clicks anywhere outside of the modal, close it\r\n");
      out.write("\t\twindow.onclick = function(event) {\r\n");
      out.write("\t\t\tif (event.target == modal) {\r\n");
      out.write("\t\t\t\tmodal.style.display = \"none\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
